[project]
authors = [{ "name" = "Volodymyr Pivoshenko", "email" = "contact@pivoshenko.dev" }]
classifiers = [
  "Development Status :: 5 - Production/Stable",
  "Environment :: Other Environment",
  "Intended Audience :: Developers",
  "Intended Audience :: Information Technology",
  "License :: OSI Approved :: MIT License",
  "Natural Language :: English",
  "Operating System :: OS Independent",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Topic :: Scientific/Engineering",
  "Topic :: Software Development",
  "Topic :: Software Development :: Libraries",
  "Topic :: Software Development :: Libraries :: Python Modules"
]
dependencies = ["click~=8.4.1", "httpx~=0.28.1", "packaging~=26.2", "tomlkit~=0.15.0"]
description = "uv-upsync - is a tool for automated dependency updates and version bumping in pyproject.toml."
keywords = [
  "dependencies",
  "dependencies-management",
  "dependencies-update",
  "dependencies-upgrade",
  "hacktoberfest",
  "packaging",
  "packaging-management",
  "packaging-update",
  "packaging-upgrade",
  "pypi",
  "python",
  "uv",
  "uv-plugin",
  "uv-plugins",
  "uv-tool"
]
license = "MIT"
maintainers = [{ "name" = "Volodymyr Pivoshenko", "email" = "contact@pivoshenko.dev" }]
name = "uv-upsync"
readme = "README.md"
requires-python = ">=3.10"
version = "2.4.1"

[project.scripts]
uv-upsync = "uv_upsync.__main__:main"

[project.urls]
Homepage = "https://github.com/pivoshenko/uv-upsync"
Repository = "https://github.com/pivoshenko/uv-upsync"

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[dependency-groups]
formatters = ["pyupgrade~=3.21.2", "ruff~=0.15.15"]
linters = ["ruff~=0.15.15", "ty~=0.0.40"]
tests = ["coverage[toml]~=7.14.1", "pytest~=9.0.3", "pytest-cov~=7.1.0", "pytest-mock~=3.15.1", "pytest-sugar~=1.1.1"]

[tool.coverage.run]
omit = ["*/__init__.py"]

[tool.pytest.ini_options]
addopts = ["--color=yes", "--cov=src", "--cov-report=term-missing"]
testpaths = ["tests"]

[tool.ty.environment]
python-version = "3.13"

[tool.ruff]
fix = true
line-length = 100
unsafe-fixes = true

[tool.ruff.format]
docstring-code-format = true
quote-style = "double"

[tool.ruff.lint]
ignore = ["COM812", "D101", "D102", "D103", "D107", "D203", "D212", "G004", "PLE1205", "TRY003", "TRY400", "TRY401"]
select = ["ALL"]

[tool.ruff.lint.isort]
force-single-line = true
from-first = false
length-sort-straight = true
lines-after-imports = 2
lines-between-types = 1
required-imports = ["from __future__ import annotations"]

[tool.ruff.lint.per-file-ignores]
"tests/*.py" = ["INP001", "PLR2004", "S101", "SLF001"]
